// <auto-generated />
using System;
using Crawford.Services.VideoStreaming.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crawford.Services.VideoStreaming.Infrastructure.Migrations
{
    [DbContext(typeof(CrawfordDbContext))]
    partial class CrawfordDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Crawford.Services.VideoStreaming.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = new Guid("183df134-28ed-4928-a816-402b6019ab90"),
                            Name = "Sample"
                        });
                });

            modelBuilder.Entity("Crawford.Services.VideoStreaming.Domain.Entities.Video", b =>
                {
                    b.Property<Guid>("VideoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Video");

                    b.HasData(
                        new
                        {
                            VideoID = new Guid("664dc446-1688-434f-be27-58070d6dcf11"),
                            CategoryID = new Guid("183df134-28ed-4928-a816-402b6019ab90"),
                            CreatedDateTime = new DateTime(2024, 10, 14, 13, 56, 49, 435, DateTimeKind.Local).AddTicks(5781),
                            Description = "Sample Video Only",
                            FilePath = "https://crawfordblobcontainer.blob.core.windows.net/videos/videoplayback.mp4",
                            ModifiedDateTime = new DateTime(2024, 10, 14, 13, 56, 49, 435, DateTimeKind.Local).AddTicks(5799),
                            ThumbnailPath = "https://crawfordblobcontainer.blob.core.windows.net/videos/df2a3c37-ff4c-452c-89fc-f4cde425f1c8.jpg",
                            Title = "Sample Video 1"
                        },
                        new
                        {
                            VideoID = new Guid("1d9c377f-1b1b-4376-926c-21b71068b923"),
                            CategoryID = new Guid("183df134-28ed-4928-a816-402b6019ab90"),
                            CreatedDateTime = new DateTime(2024, 10, 14, 13, 56, 49, 435, DateTimeKind.Local).AddTicks(5819),
                            Description = "Sample Video Only",
                            FilePath = "https://crawfordblobcontainer.blob.core.windows.net/videos/videoplayback %281%29.mp4",
                            ModifiedDateTime = new DateTime(2024, 10, 14, 13, 56, 49, 435, DateTimeKind.Local).AddTicks(5820),
                            ThumbnailPath = "https://crawfordblobcontainer.blob.core.windows.net/videos/41a57cba-0bc8-477c-8ecd-ed9693804048.jpg",
                            Title = "Sample Video 2"
                        },
                        new
                        {
                            VideoID = new Guid("d6353fa5-9a5c-4682-8df5-846b54e791b3"),
                            CategoryID = new Guid("183df134-28ed-4928-a816-402b6019ab90"),
                            CreatedDateTime = new DateTime(2024, 10, 14, 13, 56, 49, 435, DateTimeKind.Local).AddTicks(5835),
                            Description = "Sample Video Only",
                            FilePath = "https://crawfordblobcontainer.blob.core.windows.net/videos/videoplayback %282%29.mp4",
                            ModifiedDateTime = new DateTime(2024, 10, 14, 13, 56, 49, 435, DateTimeKind.Local).AddTicks(5835),
                            ThumbnailPath = "https://crawfordblobcontainer.blob.core.windows.net/videos/0d319bc7-bdbd-4655-901b-a38f58ad833e.jpg",
                            Title = "Sample Video 3"
                        });
                });

            modelBuilder.Entity("Crawford.Services.VideoStreaming.Domain.Entities.Video", b =>
                {
                    b.HasOne("Crawford.Services.VideoStreaming.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
